# Generated by Django 6.0.1 on 2026-02-12 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16, verbose_name='First name')),
                ('last_name', models.CharField(max_length=16, verbose_name='Second name')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone number')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='City/Town')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles_img/')),
                ('appointment', models.CharField(blank=True, null=True, verbose_name='Appointment')),
                ('rank', models.CharField(blank=True, choices=[('noob', 'Noob'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('god', 'God')], default='noob', null=True, verbose_name='Rank')),
                ('experiense', models.PositiveIntegerField(default=0, verbose_name='Experience points')),
                ('role', models.CharField(choices=[('admin', 'Адмін'), ('owner', 'Власник організації'), ('curator', 'Куратор'), ('student', 'Студент'), ('manager', 'Менеджер')], default='student', verbose_name='Role')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Veryfied Email')),
                ('last_logined', models.DateTimeField(blank=True, null=True, verbose_name='Last logined at')),
                ('is_active', models.BooleanField(default=False, help_text='If true allows user login into system', verbose_name='Is active user')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
